# ░█████╗░██████╗░███████╗░█████╗░████████╗███████╗██████╗░  ██████╗░██╗░░░██╗  ██████╗░███████╗██╗░░░██╗████████╗███████╗░█████╗░
# ██╔══██╗██╔══██╗██╔════╝██╔══██╗╚══██╔══╝██╔════╝██╔══██╗  ██╔══██╗╚██╗░██╔╝  ██╔══██╗██╔════╝██║░░░██║╚══██╔══╝██╔════╝██╔══██╗
# ██║░░╚═╝██████╔╝█████╗░░███████║░░░██║░░░█████╗░░██║░░██║  ██████╦╝░╚████╔╝░  ██║░░██║█████╗░░╚██╗░██╔╝░░░██║░░░█████╗░░██║░░╚═╝
# ██║░░██╗██╔══██╗██╔══╝░░██╔══██║░░░██║░░░██╔══╝░░██║░░██║  ██╔══██╗░░╚██╔╝░░  ██║░░██║██╔══╝░░░╚████╔╝░░░░██║░░░██╔══╝░░██║░░██╗
# ╚█████╔╝██║░░██║███████╗██║░░██║░░░██║░░░███████╗██████╔╝  ██████╦╝░░░██║░░░  ██████╔╝███████╗░░╚██╔╝░░░░░██║░░░███████╗╚█████╔╝
# ░╚════╝░╚═╝░░╚═╝╚══════╝╚═╝░░╚═╝░░░╚═╝░░░╚══════╝╚═════╝░  ╚═════╝░░░░╚═╝░░░  ╚═════╝░╚══════╝░░░╚═╝░░░░░░╚═╝░░░╚══════╝░╚════╝░
#
# Links:
#  Github: https://github.com/TheDevTec/AmazingFishing
#  Discord: https://discord.io/spigotdevtec


# All translation files can be found in the plugins/AmazingFishing/Translations folder
# You can create new files. The new file needs to be .yml type!
translation_file: "en"

options:
  # If Fishing points should be enabled. Players can use Points in a shop.
  # PointsManager types: VAULT, POINTS
  # VAULT - If some Economy is active plugin will use money instead of points...
  fishingPoints: "POINTS"

fishing:
  # Default fishing permissions
  permissions: 
    fish: "amazingfishing.fishing"
    # If you want different default permission to be able to catch junk items
    junk: "amazingfishing.fishing"

# Command settings  
command:
  cmds:
  - "amazingfishing"
  - "fish"
  - "af"
  permissions:
    # cmd is the default command permission ( /fish)
    cmd: "amazingfishing.command"
    reload: "amazingfishing.reload"
    open: "amazingfishing.command" # /fish open <menu>
    openOthers: "amazingfishing.command.openOthers" # /fish open <menu> <player>
    points_get: "amazingfishing.points.get" # /fish points get (player)
    points_add: "amazingfishing.points.add"
    points_remove: "amazingfishing.points.points_remove"
  # Here you can edit all help messages for each subcommand
  help:
    cmd: "&3/fish &f&l- &bOpens main menu"
    reload: "&3/fish reload &f&l- &bReload configs, menus and fishing items"
    open: "&3/fish open <menu> &f&l - &bOpens specific menu"
    openOthers: "&3/fish open <menu> <player> &f&l- &bOpens specific menu for specific player"
    points_get: "&3/fish points get (player) &f&l- &bGets players points"
    points_add: "&3/fish points add <player> <amount> &f&l- &bAdd points to a player"
    points_remove: "&3/fish points remove <player> <amount> &f&l- &bRemove points from a player"
  
# Shop settings
shop:
  # If the player should get any money, points or XP from selling fishing items
  disableMoney: false
  disablePoints: false
  disableXp: false

# Tide's Treasure
# Tide's Treasure: Daily-changing catch mechanic with unique rewards, acknowledging player skill and uncovering ocean secrets.
# Basically player will get bonus points/money/xp for certain fish. And bonus fish is changing every day (real day)
tidesTreasure:
  enabled: true
  # If the bonus fish can be the same two days in a row (or more)
  repetition: true
  apply:
    # Bonus will be applied when the player is selling bonus fish
    whenSelling: true
    # Bonus will be applied when the player catches bonus fish
    whenCatching: false
    # If this setting is true, the player will get a bonus when selling fish that was not caught on the same day (real day)
    oldFish: true
  # These are globally applied values. You can edit the bonus for each fish.
  bonus:
    money: 1.2
    points: 1.2
    exps: 1.2
    exps_catch: 1.2
  # Do not change these, please. Just if you really want to change the current bonus fish... :D
  data:
    fish: ""
    date: "2023-08-01"

















