# If this GUI should be enabled. If not, this GUI won't be loaded and you won't be able to acces it event if you are admin :D
enabled: true

# Permission that player needs to be able to open this menu
permission: "amazingfishing.menu"

# GUI size (53, 44, 35, 26, 17, 8)
size: 26

# GUI title
title: "Settings"

# If the menu is different for each player then enable this setting.
# If there are placeholders that for each player looks different (different values) then enable this setting.
# This is basically reloading items for each player again and again...
#   If items don't contain any placeholders then you can disable this. Better gui loading time.
perPlayer: true
# And yes, plugin will check permission even though this function is turned off.

items:
  records_on:
    position: 11
    displayName: "&aRecord settings"
    type: GREEN_WOOL
    lore:
    - "&fYou &acan &7receive new record messages."
    - ""
    - "&7Click to &cdisable"
    # Put here name of the file you want to open (without .yml)
    # sound: "BLOCK_BARREL_OPEN" # this is default sound :D
    # permission: "amazingfishing.menu.index"  
  records_off:
    position: 11
    displayName: "&cRecord settings"
    type: RED_WOOL
    lore:
    - "&fYou &ccan't &7receive new record message"
    - ""
    - "&7Click to &aenable"
    # Put here name of the file you want to open (without .yml)
    # sound: "BLOCK_BARREL_OPEN" # this is default sound :D
    # permission: "amazingfishing.menu.index"

# These special buttons are loaded and used differently...
buttons:
  # If you edit these items in main.yml they will be applied in all other menus (in-game).
  #  Yes you can add each item to each menu if you want.
  # IMPORTANT NOTE: If you change the size of other guis you also need to edit these "special" buttons
  # Back button
  back:
    position: 18
    type: BARRIER
    displayName: "&cBack"
  # Close button
  close:
    # Yes 'back' and 'close' buttons are in the same position. The plugin will do the rest :D
    # and yes you can change that if you want to
    position: 18
    type: BARRIER
    displayName: "&4&lClose"
    sound: "BLOCK_BARREL_CLOSE"